
server:
  port: 8002

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123
    virtual-host: test
    cache:
      channel:
        size: 50
        checkout-timeout: 3s
    template:
      retry:
        enabled: true
